
export const SET_TRAVELS_INIT_STATE = 'SET_TRAVELS_INIT_STATE';
export const SET_TRAVELS = 'SET_TRAVELS';
export const ADD_TRAVEL = 'ADD_TRAVEL';
export const REMOVE_TRAVEL = 'REMOVE_TRAVEL';
export const UPDATE_TRAVEL = 'UPDATE_TRAVEL';

