
export const SET_OFFERS_INIT_STATE = 'SET_OFFERS_INIT_STATE';
export const SET_OFFERS_LIST = 'SET_OFFERS_LIST';
export const ADD_OFFER = 'ADD_OFFER';
export const DELETE_OFFER = 'DELETE_OFFER';
export const UPDATE_OFFER = 'UPDATE_OFFER';

export const SET_OFFERS_TRAVEL = 'SET_OFFERS_TRAVEL';
export const SET_OFFERS_TRAVEL_USERS = 'SET_OFFERS_TRAVEL_USERS';
export const ADD_TRAVEL_USER = 'ADD_TRAVEL_USER';
export const REMOVE_TRAVEL_USER = 'REMOVE_TRAVEL_USER';
